run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - exportloopref

linters-settings:
  goimports:
    local-prefixes: github.com/yourorg/shlink-cli

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
